component_depth: 2
languages:
- java
- script
exclude:
- /acme-agency/acmeat/src/test/.*
- /acme-agency/acmeat/src/main/java/it/unibo/bank/generated/.*
- /acme-agency/acmeat-ws/src/test/.*
- /bankService/src/main/java/it/unibo/ws/generated/.*
- /gisService/.*
- /restaurantService/.*