component_depth: 2
languages:
- java
- script
exclude:
- /acme-agency/acmeat/src/test/.*
- /acme-agency/acmeat/src/main/java/it/unibo/bank/generated/.*
- /acme-agency/acmeat-ws/src/test/.*
- /bankService/.*
- /gisService/.*
- /deliveryService/.*
- /restaurantService/.*
- .*/build\.sh
- .*/clear\.sh